### PR TITLE
feat: ensure Mill is installed

### PR DESCRIPTION
**Pull request by ckipp01**
**The problem**

So when using this action I was a little thrown off that it was failing with:

```
java.io.IOException: Cannot run program "mill" (in directory "/home/runner/scala-steward/workspace/repos/scalacenter/bloop-config"): error=2, No such file or directory
```

I would expect the action to ensure what's needed is installed. I'm assuming no one hits on this for sbt due to it always being there in the ubuntu image.

**The fix**

This change ensures that `mill` is always there and installed.

**NOTE**

Sort of opening this up just to discuss since it came up in https://github.com/scala-steward-org/scala-steward/issues/2803. If this is an ok approach I'll add some docs. Also, I have no idea how to test this using the tool-cache. Any ideas how to test this? I see the other installations like `cs` aren't tested at all, so maybe this is fine. We could in theory do a `coursier.install('mill')`, which would be loads easier, but it's not an official way to install Mill.

### CODE REVIEW

**Comment by alejandrohdezma** [comment]
Hey @ckipp01! Great catch! Thanks for this. [This](https://github.com/coursier/apps/blob/master/apps/resources/mill.json) is what's been done when installing `Mill` through Coursier, so it should be safe to install it with just `coursier.install('mill')`. It would also ensure that the latest Mill version is installed without needing to update this action. WDYT?

**Comment by ckipp01** [comment]
> [This](https://github.com/coursier/apps/blob/master/apps/resources/mill.json) is what's been done when installing Mill through Coursier, so it should be safe to install it with just coursier.install('mill').

So the docs explicity state that this [isn't](https://com-lihaoyi.github.io/mill/mill/Intro_to_Mill.html#_coursier_unsupported) supported due to some issues running in interactive mode and looking at how Mill is ran [here](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala#L47), `-i` is being used. @lefou, sorry to ping you, but do you have any idea if using the coursier installed Mill would be fine for this usecase?

**Comment by ckipp01** [comment]
Looking more, maybe https://github.com/coursier/apps/blob/master/apps/resources/mill-interactive.json would be more appropriate? Again, no idea why there is both a `mill` and a `mill-interactive` entry.

**Comment by lefou** [comment]
## First, a bit context to the coursier installer

Older versions of Mill had two different entry points, based on the given cli args, and only an embedded script (at the head of the executable assembly jar) decided which one to use. As a consequence, coursier-based installations where never 100% correct.

In latest Mill one of the entry points (`mill.main.client.MillClientMain`) now supports all run modes, so it is working for all options. When started this way, the downside is a potential overhead due to the need to start yet another JVM process to support all configured options, e.g. `.mill-jvm-opts` in non-server mode.

No coursier launcher to date supports to start with a local configured version, so coursier-based Mill installations aren't what a typical Mill user expects.

## What we really need is a script

Currently, the proper way to run Mill is only provided by one of the following scripts:

* `mill` - shell script at https://github.com/com-lihaoyi/mill/blob/main/mill
* `millw` - POSIX shell script at https://github.com/lefou/millw/blob/main/millw
* `millw.bat` - Windows Batch script at https://github.com/lefou/millw/blob/main/millw.bat

With one of these scripts, a project specific Mill version is downloaded and run.

**Comment by lefou** [comment]
> So if I understand correctly, people using Mill will always need to fill the `mill-version` input to match the same Mill version they're using, right?

It's more kind of best practice, to stabilize the build setup. It's not strictly needed, but greatly helps to keep the whole team on the same and up-to-date version.

**Comment by ckipp01** [comment]
> So if I understand correctly, people using Mill will always need to fill the mill-version input to match the same Mill version they're using, right?

Nope, normally there is a `.mill-version` located in the workspace that mill will read from to determine what version of Mill will be launched. Just to give a couple examples:

- https://github.com/scalacenter/bloop-config
- https://github.com/com-lihaoyi/scalatags
- https://github.com/lolgab/snunit

So the `millVersion` setting in here is just to figure out what launcher version to install. That launcher should then be fine to launch other versions. Although it will be best to try to keep this up-to-date.

**Comment by alejandrohdezma** [comment]
Hey @ckipp01, I created a `mill` branch with your changes in the repository, so you can test it works. Can you update your usage to `uses: scala-steward-org/scala-steward-action@mill` and test if it downloads (and finds) Mill correctly?

**Comment by ckipp01** [comment]
> Hey @ckipp01, I created a `mill` branch with your changes in the repository, so you can test it works. Can you update your usage to `uses: scala-steward-org/scala-steward-action@mill` and test if it downloads (and finds) Mill correctly?

👍🏼 just tried it out and it was able to get it [installed](https://github.com/scalacenter/steward/actions/runs/3592944913/jobs/6049272128#step:4:35) and [use it](https://github.com/scalacenter/steward/actions/runs/3592944913/jobs/6049272128#step:4:379).

**Comment by alejandrohdezma** [comment]
`v2.31.0` and `v2` have been released including this change :)

**Pull request merged**
