### PR TITLE
Support listing repositories via a Github App

### PR DESCRIPTION
**Pull request by laughedelic**
Hi! I want to expose the functionality introduced in https://github.com/scala-steward-org/scala-steward/pull/1766 by @xuwei-k (hat tip!). The idea is that one can create a Github App and install it in the repositories they want to update from this action. 

Notice, this PR is only for using the app to list installations. It's also possible to use a GH app to authenticate, but that's another story and I will have separate PR for it.

This is a WIP, I'll think how to test it and add more details here.

### CODE REVIEW

**Comment by alejandrohdezma** [comment]
Wow! This is huge! Thank you very much @laughedelic! I will also try to test it in my own repositories. One question though, should we be adding the `--repos-file` argument to Scala Steward if we are handing the "app" ones?

**Comment by laughedelic** [comment]
> One question though, should we be adding the `--repos-file` argument to Scala Steward if we are handing the "app" ones?

Yes, I thought about it too, but it's a required argument for the Scala Steward CLI, so I'm not sure how to deal with it.
I saw in the original PR that tests have both `repos-file` and the Github app args set, but I don't know what is the behavior in that case.

**Comment by fthomas** [comment]
> I saw in the original PR that tests have both repos-file and the Github app args set, but I don't know what is the behavior in that case.

The list of repos from the GitHub App and the repos file are combined.

**Comment by laughedelic** [comment]
Great! Thanks for the clarification. So we can either have both or just create an empty file if only the app args are passed to the action.

**Comment by alejandrohdezma** [comment]
> Great! Thanks for the clarification. So we can either have both or just create an empty file if only the app args are passed to the action.

I like the idea of creating an empty file :)

**Comment by laughedelic** [comment]
It works! 🚀 Here's how I tested it.

I've set up a personal app and installed it in two test repositories: one public and one private.

<details>
<summary>Screenshot of the installation</summary>

Screenshot of the installation

Notice that the required permissions are minimal (as documented), just enough to list repositories
</details>

Then I've set up this public repo to test the action: https://github.com/laughedelic/scala-steward-runner with the reference to this branch of my fork:

```yaml
        uses: laughedelic/scala-steward-action@gh-app-args
        with:
          # used to list repositories:
          github-app-id: 104507
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
          # used to author pull requests:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
```

Here
- `SCALA_STEWARD_APP_PRIVATE_KEY` is the private key generated on the app creation
- `PERSONAL_ACCESS_TOKEN` is just a PAT with `repo` access (so PRs will be created on my behalf)

In the first successful run [logs](https://github.com/laughedelic/scala-steward-runner/runs/2082679414?check_suite_focus=true#step:2:28) you can see that it created two PRs:
- https://github.com/laughedelic/scala-steward-test1/pull/2
- https://github.com/laughedelic/scala-steward-test2/pull/2 (private 🔒)

**Comment by laughedelic** [comment]
@alejandrohdezma I think this is ready. Please, let me know if the docs are not clear enough or anything needs to be refactored.

**Comment by alejandrohdezma** [comment]
Sorry for the delay, busy week.

This is great! Thank you very much for this @laughedelic, I'm definitely changing my own projects to using this approach.

**Comment by alejandrohdezma** [comment]
Versions [`v2.13.0`](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.13.0) and [`v2`](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2) have been published containing this change

**Comment by laughedelic** [comment]
Awesome! Thanks 😊

**Pull request merged**
