### PR TITLE
use github API URL

### PR DESCRIPTION
**Pull request by mzuehlke**
* use the given URL to get tokens
* use the variable `github.api_url` as default value (https://docs.github.com/en/actions/learn-github-actions/contexts)

Fixes the secretOrPrivateKey must be an asymmetric key error
using the workaround from https://github.com/octokit/auth-app.js/issues/465#issuecomment-1549150080

fixes: #517
closes: #521

### CODE REVIEW

**Comment by alejandrohdezma** [comment]
@mzuehlke are you able to test it works using the snapshot version?

**Comment by mzuehlke** [comment]
I divided my internal working version into the 2 PRs: #520 and #521
That version is working for me 🚀

**Comment by mzuehlke** [comment]
I added the changes from my 2nd and much smaller PR here, than I can test the snapshot.

**Comment by mzuehlke** [comment]
I could very this snapshot on our on-prem runners 👍

**Review by alejandrohdezma — APPROVED** [review]

**Pull request merged**
