### PR TITLE
Update to Scala Steward 0.13 as default version

### PR DESCRIPTION
**Pull request by EwoutH**
It was released yesterday: [Scala Steward 0.13.0](https://github.com/scala-steward-org/scala-steward/releases/tag/v0.13.0).

### CODE REVIEW

**Comment by alejandrohdezma** [comment]
Hi! Thank you very much! Would you mind updating [the version in README.md](https://github.com/scala-steward-org/scala-steward-action#configuration) too? Thanks!

**Comment by EwoutH** [comment]
Good catch, done!

**Comment by alejandrohdezma** [comment]
Wow! That was quick! Thanks!

**Comment by EwoutH** [comment]
And I didn't even have time to ask about the next release, it was already there! [v2.14.0](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.14.0)

**Comment by fthomas** [comment]
Btw, this version requires the `scalafix` binary to be installed for Scalafix build migrations (https://github.com/scala-steward-org/scala-steward/pull/2308). I guess `scalafix` need to be installed similar to how `scalafmt` is installed [here](https://github.com/scala-steward-org/scala-steward-action/blob/a57c95bff174c8b29c2f9227505454025fe63889/src/main.ts#L64).

**Comment by alejandrohdezma** [comment]
I just added it and re-create `v2.14.0` release with the change. Thanks @fthomas!

**Pull request merged**
