### PR TITLE
Ensure we can run snapshot versions

### PR DESCRIPTION
**Pull request by alejandrohdezma**
For reference: https://github.com/scala-steward-org/scala-steward/pull/3102#issuecomment-1623837867

### CODE REVIEW

**Review by exoego — APPROVED** [review]

**Comment by rtyley** [comment]
> You can test it out with:
> 
> ```yaml
> uses: scala-steward-org/scala-steward-action@snapshots/514
> ```

Weirdly this snapshot version [wasn't available](https://github.com/guardian/scala-steward-public-repos/actions/runs/5484656983/jobs/9992492291) (with [this workflow config](https://github.com/guardian/scala-steward-public-repos/pull/55/commits/1b6fa7e272cdde1aa22b65e9f6d85f35e1d2dcc2)):

```
Error: Unable to resolve action `scala-steward-org/scala-steward-action@snapshots/514`, unable to find version `snapshots/514`
```

image

**Comment by alejandrohdezma** [comment]
The snapshot wasn't available after I merged the PR. But this should be possible now in version [v2.59.0](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.59.0).

**Comment by alejandrohdezma** [comment]
[Here](https://github.com/alejandrohdezma/.github/actions/runs/5486906393/jobs/9997621835#step:5:37) is an example in my own instance

**Comment by rtyley** [comment]
Thanks, just to confirm that with [v2.59.0](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.59.0) (which includes the extra fix in e28fc5f742dfc8e646bc8c5f31f1d4708fce2a3e), I was indeed able to [run a snapshot release of Scala Steward](https://github.com/guardian/scala-steward-public-repos/actions/runs/5488323839/jobs/10001015117#step:5:38)! Awesome stuff man - many thanks!

**Pull request merged**
