### PR TITLE
Add flag max-buffer-size

### PR DESCRIPTION
**Pull request by FabioPinheiro**
I would like to add the scala-steward's flag `max-buffer-size`.
But I have no idea how to test this.

### CODE REVIEW

**Comment by alejandrohdezma** [comment]
Hey @FabioPinheiro, you can use [this snapshot release](https://github.com/scala-steward-org/scala-steward-action/pull/505#issuecomment-1610923238) to test the feature if you want before merging this PR.

**Comment by alejandrohdezma** [comment]
Hey @FabioPinheiro, did you manage to test this?

**Comment by FabioPinheiro** [comment]
Hey @alejandrohdezma 
Sorry for the delay. Yes I just tested
Seems to be working.

I configured the GitHub action with the setting `max-buffer-size: 26000`
https://github.com/FabioPinheiro/scala-did/actions/runs/5598337126/jobs/10237849664
I get the following error as expected (which is the same as when I use the Steward on the docker with that setting)
`fs2.text$LineTooLongException: Max line size is 26000 but 32768 chars have been accumulated`
 
Where previously it was
https://github.com/FabioPinheiro/scala-did/actions/runs/4996284159/jobs/8949272212
`fs2.text$LineTooLongException: Max line size is 16384 but 24576 chars have been accumulated` (the defualt)

So I think it's working as expected

**Comment by alejandrohdezma** [comment]
Perfect! Thank you! I'll merge as soon as CI passes 😊

**Review by alejandrohdezma — APPROVED** [review]

**Pull request merged**
