### PR TITLE
Use os.homedir() instead of /home/runner

### LINKED ISSUE #40: Detect home directory (it's not always /home/runner)
Could we detect the home directory path when installing Coursier etc?

This action assumes that my runner has `/home/runner` as home directory.

I'm currently using a `self-hosted` runner that has `/runner` as home directory:
https://github.com/evryfs/github-actions-runner/blob/master/Dockerfile#L5

Hence I'm getting this kind of issues when trying to run this action:

```log
##[debug]Finishing: Launch Scala Steward
##[debug]Evaluating condition for step: 'Launch Scala Steward'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Launch Scala Steward
##[debug]Loading inputs
##[debug]Evaluating: secrets.PAGERO_CI_GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'PAGERO_CI_GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run scala-steward-org/scala-steward-action@v2
✓ Connected to Maven Central
##[debug]Downloading https://git.io/coursier-cli-linux
##[debug]Destination /runner/_work/_temp/304597f7-6a09-4b22-ae1b-91df41196df0
##[debug]download complete
##[debug]EACCES: permission denied, mkdir '/home/runner'
##[error] ✕ Unable to install coursier
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Launch Scala Steward
```

Could we do something like this instead to not assume the path of the home dir?

```
const homedir = require("os").homedir();
const bin = path.join(homedir, "bin");
```

Based on for example [how `olafurpg/setup-scala` does this](https://github.com/olafurpg/setup-scala/blob/8a9a839bcb747c92387be3b3f2a1b93182478ec1/src/install.ts#L5-L6).

### PR DESCRIPTION
**Pull request by MPV**
I hope this could fix #40.

Could you help me trying this out?

### CODE REVIEW

**Comment by MPV** [comment]
Unfortunately, I've run into a next issue (with a patched agent using standard homedir): it can't install scala-steward into the `/opt` directory (as per logs below). 

```log
##[debug]Evaluating condition for step: 'Launch Scala Steward'
2
##[debug]Evaluating: success()
3
##[debug]Evaluating success:
4
##[debug]=> true
5
##[debug]Result: true
6
##[debug]Starting: Launch Scala Steward
7
##[debug]Loading inputs
##[debug]Evaluating: secrets.OUR_GITHUB_TOKEN
9
##[debug]Evaluating Index:
10
##[debug]..Evaluating secrets:
11
##[debug]..=> Object
12
##[debug]..Evaluating String:
13
##[debug]..=> 'OUR_GITHUB_TOKEN'
14
##[debug]=> '***'
15
##[debug]Result: '***'
16
##[debug]Loading env
17
Run scala-steward-org/scala-steward-action@v2
18
  with:
19
    github-token: ***
20
    scala-steward-version: 0.5.0-385-e5e4789c-SNAPSHOT
21
    ignore-opts-files: true
22
    sign-commits: false
23
✓ Connected to Maven Central
24
##[debug]Downloading https://git.io/coursier-cli-linux
25
##[debug]Destination /home/runner/_work/_temp/06664612-6b19-4c8a-8b6c-ee13f23b1223
26
##[debug]download complete
27
::add-path::/home/runner/bin
28
✓ Coursier installed, version: 2.0.0-RC6-19
29
✓ Github Token provided as input
30
✓ Github Repository set to: ourorg/ourrepo
31
✓ User information retrieved from Github
32
##[debug]- Login: ourciaccount
33
##[debug]- Email: null
34
##[debug]- Name: null
35
##[debug]EACCES: permission denied, mkdir '/opt/scala-steward'
36
##[error] ✕ Unable to create Scala Steward workspace
37
##[debug]Node Action run completed with exit code 1
38
##[debug]Finishing: Launch Scala Steward
```

**Comment by MPV** [comment]
I'll investigate whether `/opt` should always been writeable (and patch the runner I use), or if it would rather make sense to install Scala Steward somewhere else instead. 

Do you have any thoughts on why we're installing Coursier into `/home/runner/bin` but not Scala Steward into that same path?

**Comment by alejandrohdezma** [comment]
Hey @MPV, `/opt` was being used since it was the original folder used by Scala Steward's own execution but it is not mandatory. I've created #42 to use the home dir instead.

**Comment by alejandrohdezma** [comment]
Can you update this PR to the latest changes in master and see if that fixes your issue? Thanks!

**Comment by MPV** [comment]
Not sure why I don't get this working when trying to run your newer version:

```log
Run scala-steward-org/scala-steward-action@3199096c
18
  with:
19
    github-token: ***
20
    scala-steward-version: 0.5.0-385-e5e4789c-SNAPSHOT
21
    ignore-opts-files: true
22
    sign-commits: false
23
✓ Connected to Maven Central
24
##[debug]Downloading https://git.io/coursier-cli-linux
25
##[debug]Destination /home/runner/_work/_temp/4d81be3e-c4c6-43d3-bc42-d8eb6a577619
26
##[debug]download complete
27
::add-path::/home/runner/bin
28
✓ Coursier installed, version: 2.0.0-RC6-19
29
✓ Github Token provided as input
30
✓ Github Repository set to: redacted/example-api
31
✓ User information retrieved from Github
32
##[debug]- Login: Redacted
33
##[debug]- Email: null
34
##[debug]- Name: null
35
##[debug]EACCES: permission denied, mkdir '/opt/scala-steward'
36
##[error] ✕ Unable to create Scala Steward workspace
37
##[debug]Node Action run completed with exit code 1
```

**Comment by MPV** [comment]
Same result with:
`Run scala-steward-org/scala-steward-action@3199096c`

**Comment by alejandrohdezma** [comment]
I think you need to re-run `npm run all` to update the `dist/index.js` file

**Comment by MPV** [comment]
Ah, I see: you build that file in a later commit. 

I tried using that now and I can confirm that it works!

Would you be up for creating a new proper release with these changes?

**Comment by alejandrohdezma** [comment]
Yep! I'll merge and create a new release right away :)

Thank you very much 😸

**Comment by alejandrohdezma** [comment]
[v2.1.2](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.1.2) has been created with latest changes. Also `v2` has been updated to point to `v2.1.2` so using `v2` should be enough.

**Pull request merged**
