### PR TITLE
Remove --whitelist and --read-only options

### PR DESCRIPTION
**Pull request by fthomas**
These are ignored because sandboxing is disabled via
[`--disable-sandbox`](https://github.com/fthomas/scala-steward/blob/e5e4789cc37a5ce7501e88f446c3aaaaf6b63c70/modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala#L37-L45).

### CODE REVIEW

**Comment by alejandrohdezma** [comment]
Wrong click 😹

**Comment by alejandrohdezma** [comment]
Since `firejail` [is already in the system](https://github.com/scala-steward-org/scala-steward-action/blob/ba9865be2446e39732d83df0688fe863e2cbab3d/Dockerfile#L3) wouldn't it easier to just remove the `--disable-sandbox`? Or we don't need `firejail` in a build like this?

**Comment by fthomas** [comment]
I think firejail doesn't work in combination with docker. There is an issue about that in Scala Steward repo.

**Comment by alejandrohdezma** [comment]
> I think firejail doesn't work in combination with docker. There is an issue about that in the Scala Steward repo.

Great to know! This is the mentioned issue BTW: https://github.com/fthomas/scala-steward/issues/347

**Comment by alejandrohdezma** [comment]
Thanks for this! :)

**Pull request merged**
